"""delete address

Revision ID: f633f7e2bfa6
Revises: 4f026b0762e4
Create Date: 2020-04-16 14:39:10.841620

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f633f7e2bfa6'
down_revision = '4f026b0762e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('address', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
